// <auto-generated />
using System;
using FurEver_Together.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurEver_Together.Migrations
{
    [DbContext(typeof(FurEverTogetherDbContext))]
<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
    [Migration("20250702210932_MySQL")]
    partial class MySQL
========
    [Migration("20250517225411_VolunteerModify")]
    partial class VolunteerModify
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FurEver_Together.DataModels.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AdoptionDate")
                        .HasColumnType("datetime(6)");

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

========
                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdoptionStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeTransportation")
                        .HasColumnType("bit");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                    b.HasIndex("UserId");

========
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("FurEver_Together.DataModels.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("FurEver_Together.DataModels.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime(6)");
========
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdopted")
<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                        .HasColumnType("tinyint(1)");
========
                        .HasColumnType("bit");
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PetId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("FurEver_Together.DataModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
========
                    b.Property<int?>("AdoptionId")
                        .HasColumnType("int");

>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
========
                    b.HasIndex("AdoptionId")
                        .IsUnique()
                        .HasFilter("[AdoptionId] IS NOT NULL");

>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FurEver_Together.DataModels.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AgreementToTerms")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver18")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AgreementToTerms")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsOver18")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PreviousExperience")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RespondDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TransportationAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PreviousExperience")
                        .HasColumnType("bit");

                    b.Property<bool>("TransportationAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FurEver_Together.DataModels.Adoption", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.Pet", "Pet")
                        .WithOne("Adoption")
                        .HasForeignKey("FurEver_Together.DataModels.Adoption", "PetId")
<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurEver_Together.DataModels.User", "User")
                        .WithMany("Adoptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pet");

                    b.Navigation("User");
========
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
                });

            modelBuilder.Entity("FurEver_Together.DataModels.ContactUs", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.User", "User")
                        .WithMany("ContactMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FurEver_Together.DataModels.Pet", b =>
                {
                    b.OwnsOne("FurEver_Together.DataModels.PersonalityProfile", "Personality", b1 =>
                        {
                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.Property<int>("Adaptability")
                                .HasColumnType("int");

                            b1.Property<int>("AffectionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AggressionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AnxietyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("EnergyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithKids")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithOtherPets")
                                .HasColumnType("int");

                            b1.Property<int>("NoiseLevel")
                                .HasColumnType("int");

                            b1.Property<int>("Playfulness")
                                .HasColumnType("int");

                            b1.Property<int>("Sociability")
                                .HasColumnType("int");

                            b1.Property<int>("Trainability")
                                .HasColumnType("int");

                            b1.HasKey("PetId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Personality")
                        .IsRequired();
                });

            modelBuilder.Entity("FurEver_Together.DataModels.User", b =>
                {
<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
                    b.OwnsOne("FurEver_Together.DataModels.PersonalityProfile", "Preferences", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Adaptability")
                                .HasColumnType("int");

                            b1.Property<int>("AffectionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AggressionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AnxietyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("EnergyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithKids")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithOtherPets")
                                .HasColumnType("int");

                            b1.Property<int>("NoiseLevel")
                                .HasColumnType("int");

                            b1.Property<int>("Playfulness")
                                .HasColumnType("int");

                            b1.Property<int>("Sociability")
                                .HasColumnType("int");

                            b1.Property<int>("Trainability")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
========
                    b.HasOne("FurEver_Together.DataModels.Adoption", "Adoption")
                        .WithOne("User")
                        .HasForeignKey("FurEver_Together.DataModels.User", "AdoptionId");

                    b.OwnsOne("FurEver_Together.DataModels.PersonalityProfile", "Preferences", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Adaptability")
                                .HasColumnType("int");

                            b1.Property<int>("AffectionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AggressionLevel")
                                .HasColumnType("int");

                            b1.Property<int>("AnxietyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("EnergyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithKids")
                                .HasColumnType("int");

                            b1.Property<int>("GoodWithOtherPets")
                                .HasColumnType("int");

                            b1.Property<int>("NoiseLevel")
                                .HasColumnType("int");

                            b1.Property<int>("Playfulness")
                                .HasColumnType("int");

                            b1.Property<int>("Sociability")
                                .HasColumnType("int");

                            b1.Property<int>("Trainability")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Adoption");
>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("FurEver_Together.DataModels.Volunteer", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.User", "User")
                        .WithOne("Volunteer")
                        .HasForeignKey("FurEver_Together.DataModels.Volunteer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurEver_Together.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FurEver_Together.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

<<<<<<<< HEAD:FurEver Together/Migrations/20250702210932_MySQL.Designer.cs
========
            modelBuilder.Entity("FurEver_Together.DataModels.Adoption", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

>>>>>>>> 18989e56a5395a8cfd1c6b6a71057581bf593b2b:FurEver Together/Migrations/20250517225411_VolunteerModify.Designer.cs
            modelBuilder.Entity("FurEver_Together.DataModels.Pet", b =>
                {
                    b.Navigation("Adoption")
                        .IsRequired();
                });

            modelBuilder.Entity("FurEver_Together.DataModels.User", b =>
                {
                    b.Navigation("Adoptions");

                    b.Navigation("ContactMessages");

                    b.Navigation("Volunteer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
